---
- project:
    merge-mode: squash-merge
    vars:
      functest_project_name: "eu-de_zuul_go"
    default-branch: main
    check:
      jobs:
        - otc-golangci-lint
    gate:
      jobs:
        - otc-golangci-lint
